# render.yaml
services:
  - type: web
    name: music-app-edu
    runtime: python
    env: production
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musicapp-edu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: cristianweindl@gmail.com  # ← Cambia por tu correo
      - key: SMTP_PASSWORD
        value: qtcrmvpqqoqsnnnj    # ← Usa una "App Password" de Gmail
      - key: EMAIL_FROM
        value: notificaciones@musiceduapp.com
      - key: BASE_URL
        value: https://https://music-app-dkh9.onrender.com/  # ← Cambia por tu URL real
      - key: ALLOWED_INSTITUTIONAL_DOMAINS
        value: instituto-escolar.es,colegio2025.es,academiamusical.edu,gmail.com  # ← Ajusta cada año

    # Activar solo si necesitas acceso SSH o logs avanzados
    healthCheckPath: /

databases:
  - name: musicapp-edu-db
    region: frankfurt
    plan: free